
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/email.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./db:/db
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - gene_search_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - gene_search_network
networks:
  gene_search_network:
    driver: bridge